apiVersion: v1
kind: Pod
metadata:
  name: attacker
  labels:
   app: attacker
spec:
 containers:
 - name: attacker
   image: xgenosama/sec_api
   imagePullPolicy: IfNotPresent
   volumeMounts:
    - name: hostsvolume
      mountPath: /attacker
   ports:
    - containerPort: 80
   securityContext: 
    privileged: true
 nodeName: ubuntu
 volumes:      
 - name: hostsvolume
   hostPath:
    path: /
          