apiVersion: v1
kind: Service
metadata:
  name: web-lb
spec:
  type: NodePort
  externalIPs:
  - 192.168.232.150
  - 192.168.232.151
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: webapp

